version: '3'
services:
  # API
  api:
          
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: ./.env
    ports:
      - "${EXPRESS_PORT}:${EXPOSED_PORT}"
   

  # SQL
  db:
    image: postgres:11.2-alpine
    container_name: database-api
    restart: always
    env_file: ./.env
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "${DATABASE_PORT}:${DATABASE_EXPOSED_PORT}"
volumes:
  db: